### ISSUE TITLE
I am new to nix. as in nix package manager. i wanna try out your configs on my arch linux with nix.

### ISSUE THREAD

**Issue by chrollorifat** [OwO-Digital/nixos-config#5]
I noticed that you are experienced with both arch and nix. So I was hoping you could write a guide for me to get started with using it? I would really really appreciate it. xoxo

**Comment by Octelly** [comment]
@chrollorifat Using GH issues for this seems kinda wrong to me, but with that out of the way...

Neither me or @Aproxia-dev are exactly experts either and both branches of our shared config are incomplete. I'd suggest you look for a better example repo (GitHub makes looking up examples extremely easy with their [advanced search](https://github.com/search/advanced)). Nix has been a huge time sink for us and you should expect the same - it is about as unique of a ecosystem as it gets.

Also, only the [Snowfall branch](https://github.com/OwO-Digital/nixos-config/tree/snowfall) (a rewrite based on [Snowfall lib](https://snowfall.org/guides/lib/quickstart/)) has any home (as in  [Home Manager](https://nixos.wiki/wiki/Home_Manager)) configurations that are installable on distros other than NixOS. _(I only did this so I could test out some stuff on my Arch desktop, otherwise I do not plan on using Nix under Arch longterm; we both already have NixOS on our laptops)_

We're both pretty busy, so don't expect much, but if you need any advice with where to start, I might be willing to give some direction on [Telegram](https://t.me/octelly). (do not ask for Discord)
